[project]
name = "smart-contract-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "aiohttp>=3.9.0",
    "rich>=14.2.0",
    "omnicoreagent>=0.2.11",
]
